services:
    waktfolio-frontend:
        hostname: waktfolio-frontend
        container_name: waktfolio-frontend
        build: ./
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - '/file:/usr/share/nginx/html/file'
        networks:
            - waktfolio-network
networks:
    waktfolio-network:
        external: true
